# Default recipe (shows help)
default:
    @just --list

# Show help
help:
    @just --list

# Clean autogenerated files
clean:
    rm -rf dist
    find . -type f -name "*.DS_Store" -ls -delete
    find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
    find . | grep -E ".pytest_cache" | xargs rm -rf
    find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
    rm -f .coverage

# Makes the venv
venv:
    uv venv
    uv sync --all-extras

# Run pre-commit hooks
format:
    uv run pre-commit run -a

# Run pytest
test:
    uv run pytest -v --cov

# Run pyright
type:
    uv run pyright

# Run all workflow (format, test, type)
run: format test type

# -----------------
#  Docker Settings
# -----------------

# Build docker images
docker-build:
    docker compose -f docker-compose.yml build --no-cache

# Start docker containers
docker-up:
    docker compose -f docker-compose.yml up -d

# Stop docker containers
docker-down:
    docker compose -f docker-compose.yml down

# Restart docker containers
docker-restart:
    docker compose -f docker-compose.yml restart

# Stop docker containers with removing volumes
docker-down-volume:
    docker compose -f docker-compose.yml down -v

# Attach to development container
docker-attach:
    docker compose -f docker-compose.yml exec dev bash
