help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

venv: ## Makes the venv
	uv venv
	uv sync --all-extras

format: ## Run pre-commit hooks
	uv run pre-commit run -a

test: ## Run pytest
	uv run pytest -v --cov

type: ## Run pyright
	uv run pyright

run: format test type ## Run all workflow


# -----------------
#  Docker Settings
# -----------------

BASE_COMPOSE  := -f docker-compose.yml

docker-build: ## Build docker images
	docker compose $(BASE_COMPOSE) build --no-cache

docker-up: ## Start docker containers
	docker compose $(COMPOSE_FILES) up -d

docker-down: ## Stop docker containers
	docker compose $(BASE_COMPOSE) down

docker-restart: ## Restart docker containers
	docker compose $(BASE_COMPOSE) restart

docker-down-volume:  ## Stop docker containers with removing volumes.
	docker compose $(BASE_COMPOSE) down -v

docker-attach: ## Attach to development container
	docker compose $(BASE_COMPOSE) exec dev bash
