# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_

  - interaction: default
  - models: jepa
  - trainers: jepa
  - buffers: sequential

  - launch: default

  - paths: default
  - hydra: default
  - shared: default

  # experiment configs allow for version control of specific hyperparameters
  - experiment: null

# You can specify `hydra.job_logging.root.level`
log_level: INFO

# Experient name of job.
experiment_name: default

# state path
saved_state: null

# Tag list of aim.
tags: []
