defaults:
  - _self_

  - dataset: cifar100
  - metrics: jepa

  - hydra: default
  - paths: default
  - shared: default

  # experiment configs allow for version control of specific hyperparameters
  - experiment: null

saved_state: ???

experiment_name: "static_metrics"

log_level: INFO

tags: []
