_target_: pamiq_core.FixedIntervalInteraction.with_sleep_adjustor
interval: ${python.eval:"1 / ${shared.video.fps}"}

agent:
  _target_: exp.agents.image_collecting.ImageCollectingAgent

environment:
  _target_: exp.envs.image_env.ImageEnvironment
  size:
  - ${shared.video.height}
  - ${shared.video.width}

  image_generator:
    _target_: exp.envs.video_frame_samplers.RandomVideoFrameSampler
    folder: ${paths.data_dir}
    extensions: ["mp4"]
    max_frames_per_video: ${python.eval:"1 * 60 * 60 * ${shared.video.fps}"}
