# VAE model configuration
_target_: exp.models.vae.create_vae
latent_dim: ${feature_size:${shared.video_shape},${shared.tubelet_size},${shared.embed_dim}}
in_channels: ${shared.in_channels}
base_channels: 32
