_target_: exp.models.vjepa.create_video_jepa
video_shape: ${shared.video_shape}
tubelet_size: ${shared.tubelet_size}
in_channels: ${shared.in_channels}
hidden_dim: 768
embed_dim: ${shared.embed_dim}
depth: 6
num_heads: 12
predictor_hidden_dim: null
predictor_depth: null
predictor_num_heads: null
