# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_

  - paths: default
  - hydra: default

# You can specify `hydra.job_logging.root.level`
log_level: INFO

# Task name of job.
task_name: ???

# Tag list of mlflow.
task_tags: []
