defaults:
  - image_generator: cifar100

_target_: pamiq_core.FixedIntervalInteraction.with_sleep_adjustor

interval: ${python.eval:"1 / ${shared.fps}"}

agent:
  _target_: exp.agents.image_collecting.ImageCollectingAgent

environment:
  _target_: exp.envs.image_env.ImageEnvironment
  transform:
    _target_: exp.envs.transform.create_transform
    size:
    - ${shared.image.height}
    - ${shared.image.width}
    device: ${shared.device}
    dtype: ${shared.dtype}
